### ISSUE TITLE
After updating graph with setData(), toggle uses old data

### ISSUE THREAD

**Issue by untamed0** [vadimmanaev/morrisjs-toggle#1]
Great work on the plugin, does exactly what I need. However I found an issue, when using morris.js' `setData()` then trying to toggle, it would switch back to the old data set. I came up with a very quick solution:

1- Graph() function, line 40 change: `this.origData = false;`
2- setYKeys() function, line 130 change to:

```
Graph.prototype.setYKeys = function (yKeys) {
    if (this.origData === false) {
        var newData = [];

        $.each(this.morris.data, function(i, v){
            newData.push(v.src);
        });

        this.origData = newData;
    }

    this.setData(this.filterData(this.origData, yKeys));
};
```

3- Add toggleUpdateData() function:

```
Graph.prototype.toggleUpdateData = function () {
    this.origData = false;
};
```

Then, when using `setData()`, also call `toggleUpdateData()` which will update the data set for morrisjs-toggle. As I said this is a quick messy solution and there is probably a better way to resolve this, but hopefully this helps someone else.

**Comment by vladimanaev** [comment]
Hi, if possible please create a pull request and I will go over it and push it in.

Vladi

**Comment by vladimanaev** [comment]
I have created and pushed a fix.

I still need to handle an issue in which you setting new data with totally new y keys.
If there is such case in which someone setting new y keys instead of creating new morris graph then I can find a solution too.
